### ISSUE TITLE
No worky

### ISSUE THREAD

**Issue by AHaymond** [aaronstaves/hubot-twss#1]
This doesn't work at all. Your `src/hubot-twss.coffee` seems to be nothing but boiler plate

**Comment by aaronstaves** [comment]
Care to elaborate? It's not responding appropriately ? Script isn't loading ? Syntax error ? 

By default it will only respond with twss to something if it's "98%" certain it should.  The reason for this is I was getting a lot of false positives when using a lower percentage like 50% or 70%

**Comment by kcm** [comment]
I needed to add 'twss' (>= 0.1.6) to the package.json deps as well. Not sure if that was the case for you. Can create a PR if desired.

**Comment by aaronstaves** [comment]
Go for it! Sorry I haven't really been maintaining this since the twss package was giving me a lot of false positives.  I'd be happy to accept any PR's though.

**Comment by kcm** [comment]
https://github.com/aaronstaves/hubot-twss/pull/2

Happy I could contribute to such a fine effort!

**Comment by aaronstaves** [comment]
Merged in and closed out.  Feel free to re-open if there are any issues
